// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoho.Data;

#nullable disable

namespace Zoho.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230425185317_seeding_data_for_currency_table")]
    partial class seeding_data_for_currency_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zoho.Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            Country = "United States",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "INR",
                            Country = "India",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "EUR",
                            Country = "Germany",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "JPY",
                            Country = "Japan",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Code = "AUD",
                            Country = "Australia",
                            IsDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
